### ISSUE TITLE
Typos/recommendations

### ISSUE THREAD

**Issue by rchappa** [complex-analysis/complex-analysis.github.io#13]
riemann_surfaces
- s/diferent/different

power_function
- s/This is reason why/This is the reason why

curves_in_the_complex_plane
- s/countour/contour
- s/counter-clockwise/counterclockwise

complex_integration
- s/analize/analyze   (a couple of times)
- s/countour/contour

integrals_of_functions_with_branch_cuts
- s/appropiate/appropriate

taylor_series
- s/convergece/convergence

**Comment by jcponce** [comment]
Thank you! All fixed!
