### ISSUE TITLE
Errores de tipeo/recomendaciones en breve_historia

### ISSUE THREAD

**Issue by rchappa** [complex-analysis/complex-analysis.github.io#14]
- s/ desarrollada por el antiguos griegos/ desarrollada por los antiguos griegos
- s/ ¿cuándo tomarón/ ¿cuándo tomaron
- s/intersecará/intersectará
- s/solición/solución
- s/usandi/usando
- s/architecto/arquitecto
- s/Esta la intuición no fue fácil/Esta intuición no fue fácil
- s/artiméticas/aritméticas
- s/Then he showed that the squared roots of negative numbers cancel each other//  (remover texto en Ingles ya traducido)
- s/aparezcen/aparecen
- s/equación/ecuación
- s/podrían ser generado/podrían ser generados
- s/es la matemática misma que nos habla/es la matemática misma la que nos habla
- s/geométircamente/geométricamente
- s/la raíz cuadrada de un negativo número/la raíz cuadrada de un número negativo
- s/la teoría de las parejas es mucho más satisfactorio/la teoría de las parejas es mucho más satisfactoria
- s/la consistencia del teoría/la consistencia de la teoría

**Comment by jcponce** [comment]
Muchas gracias! :)
