### ISSUE TITLE
Typo issue in "Complex functions"

### ISSUE THREAD

**Issue by Feya** [complex-analysis/complex-analysis.github.io#2]
Third paragraph

> A multiple-valued function can be considered as a collection of single-valued functions, each member of which is called a branch of the function. In general, we consider on particular member as a principal branch of the multiple-valued function and the value of the function corresponding to this branch as the principal branch.

I think the last word should be "value". The sentence goes as "the value of the function corresponding to this branch as the principal value".

**Comment by jcponce** [comment]
Thanks for that. 

Kind regards.

**Comment by jcponce** [comment]
Fixed. Thanks for that. 

Kind regards.
