### ISSUE TITLE
Incorrect Power Series Definitions

### ISSUE THREAD

**Issue by eamonsuo** [complex-analysis/complex-analysis.github.io#21]
On the Taylor Series page, I believe the series for sin, cos, cosh and sinh are incorrectly defined. In further pages the cos series is defined as `(-1)^n * (z^2n)/(2n!)` but on the Taylor series page the factorial value is only `n!`

![image](https://user-images.githubusercontent.com/103620628/170614208-f017211b-4732-4299-8af9-7d6229192512.png)

**Comment by jcponce** [comment]
Thanks! All fixed! :)
