### ISSUE TITLE
Typo in "Topology of the Complex Plane"?

### ISSUE THREAD

**Issue by abusch** [complex-analysis/complex-analysis.github.io#22]
On the "Topology of the Complex Plane" page, at the end of the "Classification of points" section, it says $$\partial S_3=\left\\{z:|z-\left(2+\sqrt{3}i\right)|=\frac{1}{2}\right\\}\cup\\{0\\}$$ but shouldn't it be $$\partial S_3=\left\\{z:|z-\left(2+\sqrt{3}i\right)|=\frac{1}{2}\right\\}\cup\\{\left(2+\sqrt{3}i\right)\\}$$ instead?

**Comment by jcponce** [comment]
Thanks for that. I fixed it. :)
