### ISSUE TITLE
Typo in math next to Figure 6 on the "A Brief History Page"

### ISSUE THREAD

**Issue by CameronFredrickson** [complex-analysis/complex-analysis.github.io#24]
The the first line starting with "x = " is not equal to the line below it. Perhaps the line below it should have 11*sqrt(-1) instead of the sqrt(-11) under each cubed root.
![complex-analysis-Issue](https://github.com/complex-analysis/complex-analysis.github.io/assets/7877591/52399a10-6be4-460c-85fa-402b29adcc0d)

**Comment by jcponce** [comment]
Hi Cameron,
Thanks for that. I just fixed it. :)
Kind regards.
