### ISSUE TITLE
Missing word in Chapter 1, A Brief History

### ISSUE THREAD

**Issue by Atrytone** [complex-analysis/complex-analysis.github.io#25]
![image](https://github.com/complex-analysis/complex-analysis.github.io/assets/5246036/862f4734-7a27-4b8a-a7a3-671196faa963)
Currently reads "How do interpret this value?"  Could be corrected either as "How do we interpret this value?" or "How to interpret this value?"

**Comment by jcponce** [comment]
Hi Heather

Thanks for that. I just fixed it! :)

Kind regards

**Comment by jcponce** [comment]
It should be updated in the server soon.
