### ISSUE TITLE
Typos / recommendations

### ISSUE THREAD

**Issue by rchappa** [complex-analysis/complex-analysis.github.io#26]
in brief_history

- s/how we do interpret this value?/how do we interpret this value?
- s/italian/Italian
- s/standarized/standardized
-----
in domain_coloring

- s/funcion/function
----
in integrals_of_functions_with_branch_cuts

- s/analize/analyze.
----
in taylor_series

- s/centred/centered
----
in laurent_series

- s/centred/centered
----
in classification_of_singularities

- s/centred/centered
----
in mandelbrot_set

- s/to nearest point/to the nearest point
- s/Every pixel that does not cotain/Every pixel that does not contain
- s/computer-genereted/computer-generated
----
in complex_potential_basic_examples

- s/funcion/function
- s/It is easy to generalise/It is easy to generalize
----
in flow_around_circle

- s/singularites/singularities

**Comment by jcponce** [comment]
Thanks for that. All fixed! :) Cheers!
