### ISSUE TITLE
Analytic Landscapes: applet issue

### ISSUE THREAD

**Issue by gschintgen** [complex-analysis/complex-analysis.github.io#28]
Hi, on the "Analytic Landscapes" page, there are some minor issues with the "Dynamic Exploration" applet:

By default (i.e. right when you open that page), the slider `a` changes "something" on the plot, even though the label says that it's `(z-1)/(z^2+z+1)` (without any `a`) that should be represented. This is a bit puzzling (at least in the first moment) since the text only says that there's some slider "a" without explaining what it does and there's some unexpected action when you change its value.

Only a few moments later did I realize that "a" is just some parameter for some of the other predefined functions and if I switch to one of the other examples and then back again to the first one, `a` is disabled as it should be.

**Comment by jcponce** [comment]
Hi,
Thanks for that. I fixed it.
All the best!
