### ISSUE TITLE
Possible Typo in Topology... > Classification... 

### ISSUE THREAD

**Issue by wdnaeng** [complex-analysis/complex-analysis.github.io#29]
The last two examples of the classification section state that $$S_2=\overline{B}_{\frac{7}{8}}\left(-1-\sqrt{2}i\right)$$ and 

$$S_3=\overline{B}_{\frac{1}{2}}\left(2+\sqrt{3}i\right)\setminus \lbrace2+\sqrt{3}i\rbrace $$

 where $$\text{Int } S_2=B_{\frac{7}{8}}\left(-1-\sqrt{2}\right)$$ and $$\text{Int } S_3=B_{\frac{1}{2}}\left(2+\sqrt{3}\right)$$

Am I misunderstanding the math or are we missing an i in the Int S statements?

Loving the course so far as someone that learned just enough z-plane to be dangerous in signal processing in college but had forgotten a lot of it since ;)

**Comment by wdnaeng** [comment]
Also, a request for clarification on the third example. If $S_3$ is the closed deleted neighborhood, how is it that its interior contains $z_0$ (is equal to the open neighborhood)? 

Should it maybe read $\text{Int } S_3=B_{\frac{1}{2}}\left(2+\sqrt{3}\right)\setminus \lbrace2+\sqrt{3}i\rbrace$ ?

My understanding of the previous section is that $\text{Int}$, $\text{Ext}$, and $\partial$ have no overlap, but you write that $$\partial S_3=\lbrace z:|z-\left(2+\sqrt{3}i\right)|=\frac{1}{2}\rbrace \cup \lbrace2+\sqrt{3}i\rbrace$$ which contains $z_0$.

Am I misunderstanding something fundamental?

**Comment by jcponce** [comment]
Hi! 

Thanks for reporting the typos. The imaginary constant is missing. For the second issue, yes you are right about the interior of S_3. I will fix it. 

I am you are enjoying the content of this site. 

Kind regards.

**Comment by jcponce** [comment]
All fixed now! :) By the way, the site will be down from the 25th until 31 March 2024. I will make a major update. Check the details in my Patreon:

https://www.patreon.com/jcponce

I am also working in other projects that you may like. Cheers!
