### ISSUE TITLE
Request to use

### ISSUE THREAD

**Issue by Rousan99** [complex-analysis/complex-analysis.github.io#3]
Is it alright if I use your one of the applet in my website?

**Comment by jcponce** [comment]
Hi, sure. Which one? It would be awesome if you acknowledge me too.

**Comment by Rousan99** [comment]
The complex mapping on....using webcam...and domain colouring

**Comment by jcponce** [comment]
yes cool. When you do that, please share the link of your website where you put it. Thanks for asking.

**Comment by jcponce** [comment]
So did you use the app? Where is the link to your website? I hope you can share it. Thanks
