### ISSUE TITLE
Why did you copy this page on complex integrals with branch cuts from `https://math.libretexts.org/` and still claim copywrite in your site?

### ISSUE THREAD

**Issue by prikarsartam** [complex-analysis/complex-analysis.github.io#30]
I found the same entries in [math.libretext site](https://math.libretexts.org/Bookshelves/Analysis/Complex_Analysis_-_A_Visual_and_Interactive_Introduction_(Ponce_Campuzano)/04%3A_Chapter_4/4.03%3A_Integrals_of_Functions_with_Branch_Cuts).

**Comment by jcponce** [comment]
Please, check the author in libretexts. You will be surprised.

**Comment by jcponce** [comment]
https://math.libretexts.org/Bookshelves/Analysis/Complex_Analysis_-_A_Visual_and_Interactive_Introduction_(Ponce_Campuzano)

https://complex-analysis.com/
