### ISSUE TITLE
Little typo in Limits / Recommendation

### ISSUE THREAD

**Issue by Flaviongas** [complex-analysis/complex-analysis.github.io#33]
At the end of *Limits* , in the proof, the text says: 
> Properties (10) and (13) are left as an excersie. 

when it should say:

> Properties (10) and (13) are left as an exercise. 

In *Riemann Sphere* in the beginning it says:
> For some purposes it is convenient to introduce the point to infinity

In spanish the term is "El punto al infinito", refering to a "point" that would be *at* infinity.
I think it should say:

> For some purposes it is convenient to introduce the point at infinity

**Comment by jcponce** [comment]
Thanks! I will check it soon. :)

**Comment by jcponce** [comment]
Updated! :)
