### ISSUE TITLE
False statement in limits chapter

### ISSUE THREAD

**Issue by happyboy2k** [complex-analysis/complex-analysis.github.io#34]
Hey,
I'm not very good at math so it might be I'm mistaken here but:
In the example 1 it says:
|z²-z0²| < |z-z0||z+z0|
but:
|0.9²-0.8²| = 0.81-0.64 = 0.17
and
|0.9-0.8|*|0.9+0.8| = 0.1 * 1.7 = 0.17

Greetings

**Comment by jcponce** [comment]
Thanks. I will check it soon! :)

**Comment by jcponce** [comment]
You are right. The first "<" should be "=". It is fixed, thanks. 👍

**Comment by jcponce** [comment]
And updated now.
