### ISSUE TITLE
Inacurate result when moving both point and cursor on the roots of complex chapter app 

### ISSUE THREAD

**Issue by MikHulk** [complex-analysis/complex-analysis.github.io#36]
Hello,

First thanks for this resource it is very interesting.

I think there is a little bug on [this chapter](https://complex-analysis.com/content/roots_complex_numbers.html) geogebra app (I don't know if it is due to Geogebra or en error in computation).

If I change the modulus with cursor and then move the point I didn't have the correct result after.

I took some capture before I change modulus:

<img width="1062" alt="Capture d’écran 2024-08-10 à 12 50 18" src="https://github.com/user-attachments/assets/3b995db8-0adb-412c-8745-49b1768385e5">

And after:

<img width="1062" alt="Capture d’écran 2024-08-10 à 12 51 22" src="https://github.com/user-attachments/assets/9e61ad08-5061-4130-851c-8de553227c4d">

**Comment by jcponce** [comment]
Thanks, I will check it!

**Comment by jcponce** [comment]
I see. There are some rounding issues. I will fix it!

**Comment by MikHulk** [comment]
My pleasure. Thanks again for this website.

**Comment by MikHulk** [comment]
Ah ok, I see what you've done. Looks ok on my side.

Maybe giving absolute value of Arg in absolute value is less user friendly now, but maybe you couldn't do otherwise. Having Arg as pi ratio was nice for quick checking.

**Comment by jcponce** [comment]
Thanks for your feedback.
