### ISSUE TITLE
Possible typo in "The Logarithmic Function"

### ISSUE THREAD

**Issue by Zomulgustar** [complex-analysis/complex-analysis.github.io#4]
At least one of the following appears to be the case:

1.  There is an typo in "The Logarithmic Function" section just after  "Some basic properties of the function logz are the following:" OR
2.  I have not had nearly enough caffeine today.  

The second concern is probably beyond the intended scope of your project, , but a spot-check on the first could prove helpful.  Thanks for sharing!

**Comment by jcponce** [comment]
Hi, 

Number 1 turns out to be the case. Signs were missing. :P It is fixed now. :) 

Thanks for that.
