### ISSUE TITLE
Complex Potential - Stagnation point flow applet not working

### ISSUE THREAD

**Issue by xoeg** [complex-analysis/complex-analysis.github.io#7]
Nothing happens when one clicks on the screen to start this applet.

**Comment by jcponce** [comment]
Hi, I just tested and seems to work fine. Did you try it on your desktop?

Regards

**Comment by xoeg** [comment]
I just checked, it works well for Chrome, but it does not work in Firefox. It is also the only applet where the cursor does not change when moved on top (neither Chrome nor Firefox, maybe the issue is around there)

**Comment by jcponce** [comment]
Hi, 

Thanks for the details. Yes, it was not working in Firefox. The four applets had a little difference in the code. It seems Firefox does not like the p5js function touchStarted

https://p5js.org/reference/#/p5/touchStarted

I chaged the code and it is working nice in Firefox. 

Kind regards.
