### ISSUE TITLE
The "exp" function in Roots of Complex Numbers may be confusing to new readers

### ISSUE THREAD

**Issue by joezeng** [complex-analysis/complex-analysis.github.io#8]
The paragraph in https://complex-analysis.com/content/roots_complex_numbers.html where equation (1) is introduced for the exercise introduces a bit of notation that I didn't notice anywhere earlier in the book:

> Thus, the $n$th roots of a nonzero complex number $z\neq 0$ can also be expressed as
> \begin{eqnarray}\label{expform}
> z=\sqrt[n]{r}\;**\mbox{exp}**\left[i\left(\frac{\theta}{n}+\frac{2k\pi}{n}\right)\right]
> \end{eqnarray}
> where $k=0, 1, 2, \ldots , n-1$.

You've been using e^x as the standard notation for the complex exponential up to this point, so the sudden introduction of the "exp" function will probably confuse people. Perhaps a short introduction of that notation is in order in case you use it in the future.

**Comment by jcponce** [comment]
Hi, 

Thanks for you feedback. I think you are right. I will add something soon. 

Kind regards.

**Comment by jcponce** [comment]
Ok, finally I changed it. :) Thanks again. Kind regards.
