### ISSUE TITLE
Typos / recommendations for brief_history.html 

### ISSUE THREAD

**Issue by rchappa** [complex-analysis/complex-analysis.github.io#9]
- s/rewritting/rewriting
- s/invetion/invention
- s/Excercise/Exercise    (a couple of times)
- s/nowdays/nowadays
- s/substituing/substituting
- s/refering/referring
- s/stuning/stunning
- s/to solution of the cubic equation/to the solution of the cubic equation
- s/Termonology/Terminology

**Comment by jcponce** [comment]
Hi, 
Thanks for that! All fixed! :)
